DELETE FROM plaid_category_map
WHERE (plaid_primary, plaid_detailed) IN (
    ('GENERAL_MERCHANDISE', 'GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES'),
    ('LOAN_PAYMENTS', 'LOAN_PAYMENTS_CREDIT_CARD_PAYMENT'),
    ('LOAN_PAYMENTS', 'LOAN_PAYMENTS_OTHER_PAYMENT')
);
