// schema-report introspects the migrated Postgres catalog and emits a
// deterministic Markdown report of the current schema: every table with its
// columns (type, nullability, default), constraints, and indexes (including
// partial-index predicates — a load-bearing convention in this repo).
//
// It is NOT pg_dump: it connects through the same config/DATABASE_URL layer as
// every other cmd, so the same binary produces byte-identical output locally
// (offbook_dev) and in CI (offbook_test) as long as both are migrated to the
// same head. That determinism is what lets `make schema-check` enforce the
// committed report is current.
//
// Usage:
//
//	go run ./cmd/schema-report --out ../docs/db/schema.md   # write the report
//	go run ./cmd/schema-report --out ../docs/db/schema.md --check  # fail if stale
//
// With no --out the report is written to stdout.
package main

import (
	"bytes"
	"database/sql"
	"flag"
	"fmt"
	"log"
	"os"
	"strings"

	_ "github.com/lib/pq"

	"github.com/gregwym/offbook/backend/internal/config"
)

func main() {
	out := flag.String("out", "", "path to write the report (default: stdout)")
	check := flag.Bool("check", false, "compare against --out and exit non-zero if it differs (no write)")
	flag.Parse()

	if *check && *out == "" {
		log.Fatal("--check requires --out (the file to compare against)")
	}

	cfg := config.MustLoad()
	if cfg.DatabaseURL == "" {
		log.Fatal("DATABASE_URL is empty after config.Load — refusing to run")
	}
	db, err := sql.Open("postgres", cfg.DatabaseURL)
	if err != nil {
		log.Fatalf("open db: %v", err)
	}
	defer func() { _ = db.Close() }()
	if err := db.Ping(); err != nil {
		log.Fatalf("ping db (is it migrated? run `go run ./cmd/migrate up`): %v", err)
	}

	report, err := render(db)
	if err != nil {
		log.Fatalf("render schema: %v", err)
	}

	if *check {
		existing, err := os.ReadFile(*out)
		if err != nil {
			log.Fatalf("read %s for --check: %v", *out, err)
		}
		if !bytes.Equal(existing, []byte(report)) {
			fmt.Fprintf(os.Stderr, "%s is out of date with the migrations.\nRegenerate it with `make schema` and commit the result.\n", *out)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "%s is up to date.\n", *out)
		return
	}

	if *out == "" {
		fmt.Print(report)
		return
	}
	if err := os.WriteFile(*out, []byte(report), 0o644); err != nil {
		log.Fatalf("write %s: %v", *out, err)
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", *out)
}

// render builds the full Markdown report. Everything is sorted so the output
// is a pure function of the schema, not of catalog row order.
func render(db *sql.DB) (string, error) {
	var b strings.Builder
	b.WriteString("# Offbook Database Schema\n\n")
	b.WriteString("> Generated by `cmd/schema-report` from the migrated database — **do not edit by hand**.\n")
	b.WriteString("> Regenerate with `make schema`; CI's schema-check fails if it drifts from the migrations.\n\n")

	if v, ok, err := schemaVersion(db); err != nil {
		return "", err
	} else if ok {
		fmt.Fprintf(&b, "Schema version: `%06d` (golang-migrate head)\n\n", v)
	}

	tables, err := listTables(db)
	if err != nil {
		return "", err
	}
	for _, t := range tables {
		if err := renderTable(&b, db, t); err != nil {
			return "", fmt.Errorf("table %s: %w", t, err)
		}
	}
	return b.String(), nil
}

func schemaVersion(db *sql.DB) (int64, bool, error) {
	var version int64
	err := db.QueryRow(`SELECT version FROM schema_migrations LIMIT 1`).Scan(&version)
	if err == sql.ErrNoRows {
		return 0, false, nil
	}
	if err != nil {
		// schema_migrations absent (e.g. unmigrated DB) — omit rather than fail.
		return 0, false, nil
	}
	return version, true, nil
}

func listTables(db *sql.DB) ([]string, error) {
	rows, err := db.Query(`
		SELECT c.relname
		FROM pg_class c
		JOIN pg_namespace n ON n.oid = c.relnamespace
		WHERE n.nspname = 'public' AND c.relkind = 'r'
		ORDER BY c.relname
	`)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()
	var out []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		out = append(out, name)
	}
	return out, rows.Err()
}

func renderTable(b *strings.Builder, db *sql.DB, table string) error {
	b.WriteString("## " + table + "\n\n")

	cols, err := columns(db, table)
	if err != nil {
		return err
	}
	b.WriteString("| Column | Type | Null | Default |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, c := range cols {
		null := "NOT NULL"
		if c.nullable {
			null = "null"
		}
		def := ""
		if c.def != "" {
			def = "`" + mdCell(c.def) + "`"
		}
		fmt.Fprintf(b, "| `%s` | `%s` | %s | %s |\n",
			c.name, mdCell(c.typ), null, def)
	}
	b.WriteString("\n")

	cons, err := constraints(db, table)
	if err != nil {
		return err
	}
	if len(cons) > 0 {
		b.WriteString("**Constraints**\n\n")
		for _, c := range cons {
			fmt.Fprintf(b, "- `%s`: `%s`\n", c.name, c.def)
		}
		b.WriteString("\n")
	}

	idx, err := indexes(db, table)
	if err != nil {
		return err
	}
	if len(idx) > 0 {
		b.WriteString("**Indexes**\n\n")
		for _, i := range idx {
			fmt.Fprintf(b, "- `%s`: `%s`\n", i.name, i.def)
		}
		b.WriteString("\n")
	}
	return nil
}

type column struct {
	name     string
	typ      string
	nullable bool
	def      string
}

func columns(db *sql.DB, table string) ([]column, error) {
	rows, err := db.Query(`
		SELECT a.attname,
		       pg_catalog.format_type(a.atttypid, a.atttypmod) AS type,
		       a.attnotnull,
		       COALESCE(pg_get_expr(ad.adbin, ad.adrelid), '') AS default_expr
		FROM pg_attribute a
		LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
		WHERE a.attrelid = $1::regclass
		  AND a.attnum > 0
		  AND NOT a.attisdropped
		ORDER BY a.attnum
	`, "public."+table)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()
	var out []column
	for rows.Next() {
		var c column
		var notnull bool
		if err := rows.Scan(&c.name, &c.typ, &notnull, &c.def); err != nil {
			return nil, err
		}
		c.nullable = !notnull
		out = append(out, c)
	}
	return out, rows.Err()
}

type named struct {
	name string
	def  string
}

func constraints(db *sql.DB, table string) ([]named, error) {
	// Ordered by name for determinism. pg_get_constraintdef renders the
	// canonical DDL (PRIMARY KEY / FOREIGN KEY / UNIQUE / CHECK …).
	rows, err := db.Query(`
		SELECT conname, pg_get_constraintdef(oid)
		FROM pg_constraint
		WHERE conrelid = $1::regclass
		ORDER BY conname
	`, "public."+table)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()
	return scanNamed(rows)
}

func indexes(db *sql.DB, table string) ([]named, error) {
	// Exclude indexes that merely back a constraint (PK / UNIQUE) — those are
	// already shown under Constraints. What remains is the explicit CREATE
	// INDEX set, including partial unique indexes with their WHERE predicate.
	rows, err := db.Query(`
		SELECT i.relname, pg_get_indexdef(idx.indexrelid)
		FROM pg_index idx
		JOIN pg_class i ON i.oid = idx.indexrelid
		WHERE idx.indrelid = $1::regclass
		  AND NOT EXISTS (
		    SELECT 1 FROM pg_constraint c WHERE c.conindid = idx.indexrelid
		  )
		ORDER BY i.relname
	`, "public."+table)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()
	return scanNamed(rows)
}

func scanNamed(rows *sql.Rows) ([]named, error) {
	var out []named
	for rows.Next() {
		var n named
		if err := rows.Scan(&n.name, &n.def); err != nil {
			return nil, err
		}
		out = append(out, n)
	}
	return out, rows.Err()
}

// mdCell makes a value safe inside a Markdown table cell: escape pipes and
// collapse newlines so a multi-line default can't break the row.
func mdCell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}
